---
- name : create ansible account
  hosts: all
  become: true

  tasks:
   - name: create ansible group
     group:
       name: ansible
       state: present
   - name: create ansible user
     user: 
       name: ansible
       state: present
       group: ansible
