---
# defaults file for roles/create-automation-user
ansible_automation_user: ansible 
automation_user_comment: " {{ ansible_automation_user }} automation user"
automation_user_key: /home/vagrant/.ssh/id_rsa.pub
automation_user_sudoers_file_dest: /etc/sudoers.d/{{ ansible_automation_user }}
automation_user_sudoers_line: '{{ ansible_automation_user }} ALL=(ALL) NOPASSWD:ALL'