---
ssh_key_dir: /home/vagrant/.ssh
ssh_key_name: id_rsa
ssh_key_owner: vagrant
    
authorized_key_list:
  - user: user
    public_key_path: /home/user/ansible.git/keys/id_rsa.pub
  - user: user
    public_key_path: /home/user/ansible.git/keys/jptraining_ansible_id_rsa.pub
  - user: user2
    public_key_path: /home/user/ansible.git/keys/id_rsa.pub
  - user: automatic
    public_key_path: /home/user/ansible.git/keys/jptraining_ansible_id_rsa.pub

nagios_nrpe_server_allowed_hosts_var:
  - 34.240.33.21
  - 34.243.13.208
  - 172.31.116.176
  - 172.31.105.105
  - 127.0.0.1
state: present
user_groups:
  - all
  - developpers
  - whell
users:
  - name: user1
    group: developpers
    password: "$6$nn8ko7wO$5CgwCTjhNUwugB3QqElkn1gstgWhpDsJTD2Iiyg1VVCOEp5UoFjYc9bh85RCZ1HL2rA5Ogv0/eulu4gbpTw5D."
  - name: user2
    group: sysadmins
    groups: developpers
    password: "$6$woGc.X2wfOlD3$z.zxCiMB.2toTQp9a34ss7L77curGesVYDFv7tvQI7f2cOKc9KH1FDkuQDr9OCYyS0fsaU/AktlhPujOrKHHb/"
  - name: automatic
    group: wheel

ma_variable: ma_variable group_vars/all