---
- name: "This Is The PLAY Documentation: This PLAY Runs Some Modules On The Target Hosts"
  hosts: webservers
  become: true
  tasks:
  - name: "This Is The Task Documentation: This Task Executes The Group Module On Target Hosts"
    group:
      name: "{{ item }}"
      state: present
    loop:
      - admin
      - sysadmins
      - developpers
      - wheel

  - name: "This Is The Task Documentation: This Task Creates Users On Target Hosts"
    user:
      name: "{{ item.name }}"
      group: "{{ item.group | default(omit) }}"
      groups: "{{ item.groups | default(omit) }}"
      password: "{{ item.password | default(omit) }}"
      state: present
    loop:
      - { name: developper1, groups: "developpers, sysadmins", password: password1 | password_hash('sha512') }
      - { name: developper2, group: admin, groups: developpers, password: password2 | password_hash('sha512') }
      - { name: automatic, group: wheel }
