--- 
- name: PLAY sur l'utilisation des variables registered
  hosts: all
  tasks: 
  - name: Set variable 'ma_variable' 
    set_fact: 
      ma_variable: ma_variable set_fact

  - name: Print variable 'ma_variable' 
    debug: 
      msg: '{{ ma_variable }}'