--- 
- name: PLAY sur l'utilisation des variables include_vars
  hosts: webservers  
  tasks: 
  - name: Utilisation du module include_vars
    include_vars:
      file: include_vars.yaml
      name: mes_variables_include_vars

  - name: Print variable 'mes_variables_include_vars' 
    debug: 
      msg: '{{ mes_variables_include_vars }}'

  - name: Print variable 'mes_variables_include_vars' 
    debug: 
      msg: '{{ mes_variables_include_vars.ma_variable }}'   

  - name: Print variable 'ma_variable' 
    debug: 
      msg: '{{ ma_variable }}'      